
sudo: false

language: node_js

node_js:
  - "6"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

install:
  - npm config set spin false
  - npm install -g npm@latest

  - npm install

script:
  - "npm i karma"
  - "NODE_ENV=test karma start"
  - "NODE_ENV=production node node_modules/.bin/webpack && cp app/index.html public/index.html"

notifications:
  slack: stackriot:gLki5FxZeKzaSziW26HP0DJm
