language: node_js
node_js:
  - "node"
  - "iojs"
  - "6.0"
  - "5.0"
  - "4.2"
  - "0.12"
  - "0.10"

script:
  - "npm i karma"
  - "NODE_ENV=test karma start"
  - "npm install coveralls"
  - "npm i"
  - "NODE_ENV=production node node_modules/.bin/webpack && cp app/index.html public/index.html"
  - "npm i snyk-protect"

after_script:
  - "make test-coveralls"
  - "npm run snyk-protect"

notifications:
  slack: stackriot:gLki5FxZeKzaSziW26HP0DJm

before_install: if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
